openapi: 3.0.0
info:
    title: Theatro
    version: 1.0.0
    description: ''
servers:
    - url: '{{baseUrl}}'
    - url: localhost
paths:
    /login:
        post:
            summary: Login
            tags:
                - Auth
            responses: {}
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                mail:
                                    type: string
                                    format: email
                                password:
                                    type: string
    /register:
        post:
            summary: Register
            tags:
                - Auth
            responses: {}
    /choose-password:
        patch:
            summary: Choose Password
            tags:
                - Auth
            parameters:
                - name: deprecated
                  in: query
                  required: false
                  schema:
                      type: boolean
            responses: {}
    /event/show:
        post:
            summary: Create show
            tags:
                - Event
                - Show
            responses: {}
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                dateTimeStart:
                                    type: string
                                dateTimeEnd:
                                    type: string
                                location:
                                    type: string
                                memberMax:
                                    type: integer
                                roles:
                                    type: array
                                    items:
                                        type: string
    /show/6901ded3a9fc93e47dd0998d/apply:
        post:
            summary: Apply to show
            tags:
                - Event
                - Show
            responses: {}
    /show/{showId}:
        get:
            summary: Get show
            tags:
                - Event
                - Show
            responses: {}
        parameters:
            - name: showId
              in: path
              required: true
              schema:
                  deprecated: false
    /show/6901ded3a9fc93e47dd0998d/applications:
        get:
            summary: List applications for show
            tags:
                - Event
                - Application
            responses: {}
    /application/{applicationId}/process:
        patch:
            summary: Update application of member
            tags:
                - Event
                - Application
            responses: {}
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                status:
                                    type: string
                                notes:
                                    type: string
        parameters:
            - name: applicationId
              in: path
              required: true
              schema:
                  deprecated: false
    /event/workshop:
        post:
            summary: Create workshop
            tags:
                - Event
                - Workshop
            responses: {}
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                dateTimeStart:
                                    type: string
                                    format: style
                                dateTimeEnd:
                                    type: string
                                location:
                                    type: string
                                memberMax:
                                    type: integer
    /workshop/{workshopId}/apply:
        post:
            summary: Apply to workshop
            tags:
                - Event
                - Workshop
            responses: {}
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                availability:
                                    type: string
        parameters:
            - name: workshopId
              in: path
              required: true
              schema:
                  deprecated: false
    /workshop/{workshopId}:
        get:
            summary: Get workshop
            tags:
                - Event
                - Workshop
            responses: {}
        parameters:
            - name: workshopId
              in: path
              required: true
              schema:
                  deprecated: false
    /:
        post:
            summary: Create workshop
            tags:
                - Event
                - Workshop
            responses: {}
    /event:
        get:
            summary: Get all events
            tags:
                - Event
            parameters:
                - name: type
                  in: query
                  required: false
                  schema:
                      type: string
            responses: {}
    /event/{eventType}/{eventId}/followup:
        get:
            summary: Follow up event
            tags:
                - Event
            responses: {}
        parameters:
            - name: eventType
              in: path
              required: true
              schema:
                  deprecated: false
            - name: eventId
              in: path
              required: true
              schema:
                  deprecated: false
    /member/{memberId}:
        get:
            summary: Get member
            tags:
                - Member
            responses: {}
        parameters:
            - name: memberId
              in: path
              required: true
              schema:
                  deprecated: false
